### ISSUE TITLE
Seems to be broken recently :-(

### ISSUE THREAD

**Issue by N7DR** [matteason/daily-cloud-maps#8]
Trying to find a good source of cloud data is a real pain, isn't it?

Up until recently I was using:
https://raw.githubusercontent.com/apollo-ng/cloudmap/master/global.jpg
but that seems to have stopped updating sometime recently.

Looking for a new map, I discovered your project, but your advice to use:
https://matteason.github.io/daily-cloud-maps/8192x4096-clouds.jpg
seems no longer to be valid :-(

That page exists, but the text on page:
https://matteason.github.io/daily-cloud-maps/8192x4096-clouds.jpg
says that the image hasn't been updated in about a week, and the map itself has obvious problems if you look at it :-(

Anyway, I thought I'd bring that to your attention.

It's amazing that nearly a quarter of the way through the 21st century, there doesn't seem to be a reliable place to find reasonably current global cloud maps.

**Comment by matteason** [comment]
Sorry, yeah, it's really frustrating. I have been experimenting with other sources - the main sticking point is that other whole-earth images (eg [EUMETSAT's Geostationary Ring IR10.8 μm Image - Multimission](https://data.eumetsat.int/product/EO:EUM:DAT:0330#)) are only ever infrared, and that doesn't give as good a quality image as combining true colour with cloud confidence. You lose a lot of cloud detail because the sea and land surface temperatures affect the image and wash out the clouds. But something is better than nothing, so I'm probably going to have to bite the bullet and switch over to that instead

**Comment by matteason** [comment]
Update on this in https://github.com/matteason/daily-cloud-maps/discussions/9

**Comment by matteason** [comment]
New, more reliable service now launched at https://github.com/matteason/live-cloud-maps
